---
version: "3"

services:
  3x-ui:

    container_name: 3x-ui
    hostname: ${HOST}
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "true"
    env_file:
      - .env
    tty: true
    network_mode: host
    restart: unless-stopped
